### ISSUE TITLE
Project 2 Roadmap

### ISSUE THREAD

**Issue by lasalvavida** [SKravitsky/ECEC412#2]
This is a roadmap issue for the completion of Project 2 due 10/25.

This splits up the existing single-cycle architecture into a multi-cycle CPU through
the addition of the following components:
- [x] IR (Instruction Register) (#3) (Assigned to: @lasalvavida) (PR: #14)
- [x] MDR (Memory Data Register) (#4) (Assigned to: @lasalvavida) (PR: #14)
- [x] MulticycleControl (#5) (Assigned to: `none`)
- [x] MulticycleCPU (#6) (Assigned to: `none`)
- [x] MUX3Way (#7) (Assigned to: @Jayx239) (PR: #15)
- [x] MUX4Way (#8) (Assigned to: @Jayx239) (PR: #16)
- [x] PCMulticycle (#9) (Assigned to: `none`)
- [x] RegA (#10) (Assigned to: @SKravitsky) (PR: #17)
- [x] RegB (#11) (Assigned to: @SKravitsky) (PR: #17)
- [x] RegistersMulticycle (#12) (Assigned to: @SKravitsky)
- [x] DataMemoryMulticycle (#13) (Assigned to: `none`)

Claim a part and I'll update the assignments.

**Comment by Jayx239** [comment]
I'll take the MUX3Way and MUX4Way

**Comment by SKravitsky** [comment]
I can take a shot at the RegA, RegB, and Registers Multicycle
I can also take a look at the DataMemoryMulticycle when I get a chance.

**Comment by Jayx239** [comment]
I'll take #13 DataMemoryMulticycle, instead of #5

**Comment by jakibayo03** [comment]
I can take the MulticycleControl and MulticycleCPU

EDIT: Didn't see Jake say he would also take the MulticycleControl. I can take the PC then

**Comment by lasalvavida** [comment]
Closed via #19
